import random
list_of_questions = [
    "What topic can you bring up at a family gathering to instantly get everyone riled up?",
    "What would be the best and worst part of being a cat in your opinion?",
    "What would you do if you saw a giraffe on the side of the road?",
    "If you could change one thing about your family, what would it be?",
    "Does your family have any weird traditions?",
    "What is the assumption that people make about you that's totally wrong?",
    "What's something uncomfortable but you feel everyone should experience at least once in their life?",
    "What food do you have a love-hate relationship with?",
    "What's your favorite thing to do when you're all alone?",
    "What is something that you like that your parents do?",
    "What is socially acceptable today that you think won't be in 10 years?",
    "How well do you trust your gut feelings?",
    "What is money to you?",
    "What was a situation you thought would be terrible but you actually enjoyed it?",
    "What's your good luck charm?",
    "Is time currently passing quickly or slowly for you?",
    "Where was your secret hiding place as a child?",
    "What's something that you completely don't understand?",
    "Is there anything that makes you far angrier than it should?",
    "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
    "How many things you currently own do you think you could throw away and not notice a difference in your life?",
    "What are you currently doubting in your life?",
    "Do you believe there is only one other person in the world for you or many?",
    "How much damage could your best friend do to you if you ever had a falling out?",
    "What line from a song has had the biggest impact on you?",
    "Is there any place that you have no desire to visit? Why?",
    "What's the embarrassing story that your parents used to tell others about you?",
    "What was the last dream you can remember about?",
    "What was a situation where you literally did a doubletake?",
    "How would you describe someone who is wealthy?",
    "What do you think people pretend to like when they really don't?",
    "What's the most recent interesting conversation you had?",
    "What is your current favorite TV show? What was it 5 years ago?",
    "What law have you broken the most in your life?",
    "What's your opinion on naps?",
    "What will be your go-to story when you're old?",

    "Do you people watch? If so, where do you like to do this most?",
    "Have you ever been punished for something you didn't do?",
    "What's your story about breaking the law?",
    "What thing have you been procrastinating about that you will begin doing today?",
    "What book or movie character can you see in your own life?",
    "What's an interesting fact that you recently learned?",
    "If someone were to sum you up with a phrase, what would that phrase be?",
    "What food have you never tried?",
    "What's the one thing that you seem to constantly lose?",
    "What would you be really good at if it wasn't for one thing?",
    "What activity do you do where your mind wanders in thoughts the most?",
    "Would you consider yourself decisive or indecisive?",
    "How do you best like your ice-cream?",
    "Of all the problems in the world, which one would you like to see solved first?",
    "What does nobody want to talk about, but really should?",
    "What's your biggest first world problem?",
    "What was your last 'ah-ha' moment?",
    "What is something you own that you have never used?",
    "Do you name inanimate objects?",
    "How do you approach life?",
    "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
    "What's your knowing just enough to be dangerous story?",
    "What law have you broken the most in your life?",
    "What destination is at the top of your list to visit?",
    "What argument did you have that looking back on was absolutely ridiculous?",
    "Do you have any phobias?",
    "What's your story about being under intense pressure and how did you handle it?",
    "What do you think is your most creative ability?",
    "What's the last thing you complained about?",
    "Where is the last place you've been where you felt completely out of place?",
    "What is something that you like that your parents do?",
      
    "If someone were to sum you up with a phrase, what would that phrase be?",
    "If you had to pick a single word to describe this year so far, what would it be?",
    "What was a situation where you literally did a doubletake?",
    "What's your opinion on naps?",
    "How much damage could your best friend do to you if you ever had a falling out?",
    "Do you have a nightmare travel story?",
    "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
    "Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?",
    "Who have you met only one time that left a huge impression on you?",
    "What do you know is bad for you but you continue to do it anyway?",
    "Do you have something special that picks you up when you feel down? What is it?",
    "What question have people recently been constantly asking you?",
    "What do you like best about yourself?",
    "If it's raining outside, what activity do you most want to do?",
    "What is a restaurant you refuse to eat at and why?",
    "What situation is sure to make you cry?",
    "What do you do in secret that you're proud of?",
    "If you could change the color of one thing, what would it be and why?",
    "Do you have a dream job in mind? What would it be?",
    "What's your plan for surviving a zombie invasion?",
    "If you were going to start your own business, what would it be?",
    "What's the best part of rain?",
    "What type of exercise do you like most?",
    "What is your opinion on tattoos?",
    "What is your favorite spice?",
    "What do you wish they would teach at school that they don't?",
    "What's the most amount of money you've ever found? What was the situation?",
    "What's the most interesting thing you have in your pockets right now?",
    "What is the most recent silly thing you did?",
    "What is the most recent life lesson you've learned?",
    "What mode of transportation have you never tried?",
    "What's one thing you think you should be doing more often?",
    "What's the story behind your favorite memento?",
    "What would someone who doesn't know you well be most surprised about?",
    "Do you have a reoccurring dream?",
    "What uncommon thing would you like to see become more common?",
    "What have you recently felt grateful for?",
   
    "Do you believe that money can make you happy?",
    "What's your current biggest worry?",
    "Are there any words that you simply can't stand?",
    "What is your opinion on social media?",
    "What's the best trick someone has ever played on you?",
    "Do you have a dream job in mind? What would it be?",
    "What's the most difficult thing about being you?",
    "Would the world be better or worse if superheroes existed?",
    "If you could choose to be famous for something, what would it be?",
    "What one thing would significantly make your life better?",
    "What do you think would be the worst thing about being famous?",
    "Is there anyone that you're wondering about and if they're okay?",
    "What do you try to do to make the world a little better?",
    "How do you usually react if you receive bad service?",
    "What's the most spontaneous thing you've ever done?",
    "What is the most selfish thing you do that you're okay with?",
    "Where's the next place you want to visit?",
    "What is your current philosophy about money?",
    "What have you done that you didn't like, but would you be willing to give it another shot?",
    "If you were handed $500 at this moment, how would you spend it?",
    "What do you know how to do that's useless?",
    "What's the worst accident you ever had?",
    "What recent event have you seen that restored your faith in humankind?",
    "What's the best compliment you ever received?",
    "What were you most afraid of when you were younger? Do you still have that fear?",
    "What did you recently learn the hard way?",
    "What small stuff do you sweat even though you know you shouldn't?",
    "What recent thing have you decided that you're completely over and done with?",
    "If you could only ask one question to each person you meet, what would that question be?",
    "If you could play a prank on any historical figure, who would you pick and what prank would you do?",
    "Does your family have any weird traditions?",
    "Where do you see yourself in 5 years?",
    "What's the last thing you did alone and you enjoyed?",
    "Have you ever had or witnessed a drop the mic moment?",
    "Who is someone you recently thought about that you haven't seen or talked to in years?",
    "What do you consider to be the smartest thing you've ever done in your life so far?",
    "What's the last thing you complained about?",
    "What part of the human face do you look at when you talk to someone?",
    "What were you most afraid of when you were younger? Do you still have that fear?",
    "Have you ever had a terrible house guest? If so, what happened?",
    "What the best thing that can happen in the first 5 minutes after waking up?",
    "Where was your secret hiding place as a child?",
    "What is the last big goal you accomplished?",
    "What is the oddest form of entertainment you enjoy?",
    "When you're by yourself, what do you usually think about?",
    "What part of history do you find most interesting?",
    "What is your biggest regret from the last month?",
    "What's something that you think you may have been the only person in the world to ever do?",
    "What is something you predict will exist in 10 years that doesn't today?",
    "What holiday do you think more people should celebrate?",
    "What was the last meltdown that you witnessed?",
    "Of all the things you've bought in your life, what has been the worst purchase?",
    "Which of your past teachers would you like to sit down with and talk to today?",
    "Do you have any secret hobbies?",
    "If you were to be famous for something, what would that be?",
    "What was a past passion that you can't believe you were so passionate about?",
    "What's your favorite daily routine?",
    "What is your current philosophy about money?",
    "What's something about you today that the old you would find surprising?",
    "What did you recently learn the hard way?",
    "What's the embarrassing story that your parents used to tell others about you?",
    "What would you do if you saw a giraffe on the side of the road?",
    "What uncommon thing would you encourage everyone to try once?",
    "What types of things do you doodle?",
    "How many chances do you give a person before you write them off?",
    "What would be the best thing about losing your hearing?",
    "What do you know how to do that's useless?",
    "What's something that was completely out-of-character that you did?",
    "What do you believe is the biggest thing that's currently holding you back from success?",
    "Do you remember what the first school report you wrote was about?",
    "Who in your family can't you believe you're related to?",
    "Do you have a favorite brand?",
    "What is the assumption that people make about you that's totally wrong?",
    "What are the top three qualities you admire in others?",
    "What is something that you find mildly annoying, but not annoying enough to do anything about?",
    "What do you try to do to make the world a little better?",
    "What future year are you most looking forward to arriving?",
    "What's the story behind your last rant?",
    "What question have people recently been constantly asking you?",
    "If everyone here was a color, what color would each person be?",
    "Do you have any phobias?",
    "Have you been given any good advice lately?",
    "What's your favorite daily routine?",
    "How do you entertain yourself when you're bored?",
    "What is something that you absolutely will not put up with?",
    "If you knew you could live forever, how would you spend your days differently?",
    "What's your opinion on tipping?",
    "Do you think you're more like your mom or your dad?",
    "What doesn't exist, but should?",
    "What would your dream day look like?",
    "Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?",
    "Where is the last place you've been where you felt completely out of place?",
    "What were you most afraid of when you were younger? Do you still have that fear?",
    "Are you currently where you want to be in life?",
    "What's an example of when you changed your mind?",
    "What are the top three characteristics you feel are important for a person?",
    "What uncommon thing would you encourage everyone to try once?",
    "When you're by yourself, what do you usually think about?",
    "If you were going to start your own business, what would it be?",
    "Have you ever had a terrible house guest? If so, what happened?",
    "Do you have a reoccurring dream?",
    "What's something others purchase that you simply can't understand why?",
    "What's something that you know that few other people know?",
    "What bad decision did you make that actually turned out to be a good decision?",
    "What do you think would be the worst thing about being famous?",
    "What's some small thing you recently noticed?",
    "What do you think is the most valuable resource?",
    "How much damage could your best friend do to you if you ever had a falling out?",
    "Do you remember what the first school report you wrote was about?",
    "What is something that you learned from simply watching a stranger?",
    "What thing from childhood do you still enjoy to this day?",
    "What's most important to you about your school/work environment?",
    "What was the last meltdown that you witnessed?",
    "What is the messiest situation you've ever encountered?",
    "What do you wish you had learned five years before you did?",
      
    "Is there any place that you have no desire to visit? Why?",
    "How many things you currently own do you think you could throw away and not notice a difference in your life?",
    "What will be your go-to story when you're old?",
    "What's an interesting fact that you recently learned?",
    "Do you believe that money can make you happy?",
    "What is the next thing you have on your to-buy list?",
    "What's something you find attractive that others may not?",
    "If you had to change the language you speak, which one would you choose?",
    "What challenge would you like to see your best friend take on?",
    "Do you have any secret hobbies?",
    "What song currently speaks to you the most?",
    "What is something you predict will exist in 10 years that doesn't today?",
    "What small stuff do you sweat even though you know you shouldn't?",
    "What do you believe is the biggest thing that's currently holding you back from success?",
    "What sound will instantly melt your heart?",
    "Is there a personality trait that you'd like to adopt from one of your friends?",
    "What's your opinion on cell phones?",
    "How difficult is it for you to try new things?",
    "What is the most recent life lesson you've learned?",
    "Do you, or did you in the past, have any strange habits?",
    "If you had to pick a single word to describe this year so far, what would it be?",
    "What argument did you have that looking back on was absolutely ridiculous?",
    "What's your story about breaking the law?",
    "What do you think people pretend to like when they really don't?",
    "If you could choose the way you became a hero, what would the circumstances be?",
    "What's something that you know you should start, but haven't?",
    "If you could choose to be famous for something, what would it be?",
    "What photo have you recently seen that spoke to you?",
    "What is the most recent fact you learned that surprised you?",
    "What's the next line to cross off your list?",
    "What is something you thought would be a great idea but was terrible when you actually did it?",
    "What's simply too difficult?",
    "What is your best shower thought?",
    "What's the most recent interesting conversation you had?",
    "What's the story behind your favorite memento?",
    "Has someone ever done a random act of kindness to you?",
    "What's the story behind your greatest treasure?",
    "What do you wish you had more talent doing?",
    "Have you ever had or witnessed a drop the mic moment?",
    "Do you have a dream job in mind? What would it be?",
    "What thing have you been procrastinating about that you will begin doing today?",
    "What is something that someone does that will immediately turn you off?",
    "If you could play a prank on any historical figure, who would you pick and what prank would you do?",
    "What do you consider to be the smartest thing you've ever done in your life so far?",
    "Have you evet taken a long shot that worked out?",
    "What holiday do you think more people should celebrate?",
    "What type of exercise do you like most?",
    "What have you recently felt grateful for?",
    "What part of your body currently doesn't feel 100%?",
    "What's your good luck charm?",
    "On any given day, what do you think you spend the most time doing?",
    "What have you recently realized you have been doing wrong?",
    "What are you currently doubting in your life?",
    "What's something that you find difficult, but you think in your mind it should be easy?",
    "What memory have you been thinking about a lot lately?",
    "What's your 'famous person' story?",
    "Who is someone you recently thought about that you haven't seen or talked to in years?",
    "What's something that was completely out-of-character that you did?",
    "What's one thing you think you should be doing more often?",
    "What's the worst accident you ever had?",
    "Who is the luckiest person you know?",
    "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
    "What is money to you?",
    "Have you ever let someone else get punished for something you did?",
    "What is the last thing that you totally overreacted to?",
    "What do you think is your most creative ability?",
    "What is something you own that you have never used?",
    "Have you ever had a missed connection encounter?",
    "What is your opinion on tattoos?",
    "What do you secretly hoard?",
    "Is there anything that most people find cute that creeps you out?",
    "How many chances do you give a person before you write them off?",
    "What food combination do you eat that makes others cringe?",
    "What recent experience made you feel old?",
    "What little thing instantly tells you that a person is good?",
    "What is your opinion on tattoos?",
    "What is the oddest form of entertainment you enjoy?",
    "What's the story behind why you replaced the last phone you had?",
    "How would you describe someone who is wealthy?",
    "Have you ever seen a movie that you thought was better than the book?",
    "What is the next skill that you'd like to learn really well?",
    "What do you see happening in your future?",
    "Who in your family can't you believe you're related to?",
    "What about you do you seem to get the most comments about?",
    "What topic can you bring up at a family gathering to instantly get everyone riled up?",
    "What's the biggest wager you've ever made?",
    "What has been your biggest financial mistake?",
    "What is the last big goal you accomplished?",
    "What have you done that you didn't like, but would you be willing to give it another shot?",
    "What's the worst piece of advice you ever got from someone?",
    "What recent thing have you decided that you're completely over and done with?",
    "What's something that you believe that most other people don't?",
    "What was a situation you thought would be terrible but you actually enjoyed it?",
    "Is there anything that makes you far angrier than it should?",
    "What was a past passion that you can't believe you were so passionate about?",
    "What's the most interesting thing you have in your pockets right now?",
    "What is the funniest false thing you were able to convince others that's true?",
    "Are there any words that you simply can't stand?",
    "What is it that motivates yourself the most?",
    "Have you ever done something embarrassing around a former crush?",
    "What's the best compliment you ever received?",
    "What's your opinion on naps?",
    "What's your story about being under intense pressure and how did you handle it?",
    "What law have you broken the most in your life?",
    "What is the last big argument you go into and who was it with?",
    "Do you have a bucket list?",
    "How far back can you trace your family tree?",
    "What is the easiest way to bring a smile to your face?",
    "Do you enjoy people watching?",
    "What is the most unique cloud you've ever seen in the sky?",
    "If you had to wear a hat for the next week, what type of hat would you choose?",
    "What's the most difficult thing about being you?",
    "What do you like to do that's traditionally considered masculine?",
    "How would you spend $1,000 to give the most happiness to the most number of people possible?",
    "How well do you think you understand yourself?",
    "If it's raining outside, what activity do you most want to do?",
    "What is the quickest way for you to lose respect for someone?",
    "What do you think is the most complex aspect about yourself?",

    "Do you people watch? If so, where do you like to do this most?",
    "What does nobody want to talk about, but really should?",
    "What have you been thinking about lately that has kept you up at night?",
    "How long did it take for you to come up with your current signature?",
    "What's something that you never seem to get tired of doing?",
    "Do you have a favorite brand?",
    "What was your last 'ah-ha' moment?",
    "What weird thing do you do when nobody else is around?",
    "If you knew the winning lottery numbers, would you keep them to yourself or share with others?",
    "Have you ever been at an event that you think will one day be in history books?",
    "How do you usually react if you receive bad service?",
    "What the best thing that can happen in the first 5 minutes after waking up?",
    "What country sounds interesting but you know very little about?",
    "What is the most recent silly thing you did?",
    "What's your favorite room in your house and why?",
    "What recent situation was nearly a disaster, but you were able to prevent it?",
    "What's your biggest first world problem?",
    "What's something that is common today that humans will be embarrassed about doing in 50 years?",
    "What food do you have a love-hate relationship with?",
    "How much money would you need in the bank to feel comfortable to retire today?",
    "What's something that you would be willing to stay up all night to do?",
    "What can you talk about for hours?",
    "If you could lock someone up and throw away the key, would you and if so, who would that be?",
    "What do you know how to do that's useless?",
    "What is something that has had a big impact on your that you observed from afar?",
    "What's the best way you've found to calm yourself when you get stressed?",
    "What is your current philosophy about money?",
    "What is the last encounter you had with a random stranger?",
    "What was the best thing you learned in the past year?",
    "How long do you think you could survive on your own?",
    "Do you have a special project you're currently working on?",
    "   ",
    "If you had to choose, would you rather be too hot or too cold?",
    "What's your favorite ritual?",
    "What did you learn from the last book you read?",
    "What was the last thing that truly disappointed you?",
    "What's something interesting about you that few people know?",
    "Where do you draw the line?",
    "What's the most difficult choice you were asked to make?",
    "What's your plan for surviving a zombie invasion?",
    "If you could describe your current life as a movie, which movie would you choose?",
    "If it was possible to transplant your brain to stay alive for another 100 years, would you?",    
    "What's something others purchase that you simply can't understand why?",
    "What is your favorite spice?",
    "If you could choose the way you became a hero, what would the circumstances be?",
    "Is there a personality trait that you'd like to adopt from one of your friends?",
    "What food combination do you eat that makes others cringe?",
    "What uncommon thing would you like to see become more common?",
    "How do you best like your ice-cream?",
    "What is the last big goal you accomplished?",
    "What are the top three characteristics you feel are important for a person?",
    "How do you make decisions?",
    "What is the easiest way to bring a smile to your face?",
    "What has been your 15 minutes of fame up to this point?",
    "What activity do you do where your mind wanders in thoughts the most?",
    "What's something that you believe you'll never be able to do well?",
    "If you had to choose, would you rather be too hot or too cold?",
    "How do you usually react if you receive bad service?",
    "Do you people watch? If so, where do you like to do this most?",
    "What's the way you find yourself procrastinating most?",
    "What do you think is the most valuable resource?",
    "What would your dream day look like?",
    "What's your go-to funny story now, but was horrendous at that moment?",
    "What do you like to do that's traditionally considered masculine?",
    "What song do you secretly sing in the shower?",
   
    "What's the last goal you set for yourself that you accomplished?",
    "Have you ever taken a long shot that worked out?",
    "How many chances do you give a person before you write them off?",
    "What's your opinion on cell phones?",
    "What's the embarrassing story that your parents used to tell others about you?",
    "What is the oddest form of entertainment you enjoy?",
    "What would be the best and worst part of being a cat in your opinion?",
    "What would be the best thing about losing your hearing?",
    "What do you consider the most difficult food to eat?",
    "What is the last thing that you totally overreacted to?",
    "Do you have any secret hobbies?",
    "What is the most interesting class you've ever taken?",
    "What do you remember most about your first crush?",
    "What country sounds interesting but you know very little about it?",
    "What types of things do you procrastinate the most on?",
    "Is there anything that most people find cute that creeps you out?",
    "How much damage could your best friend do to you if you ever had a falling out?",
    "What have you been thinking about lately that has kept you up at night?",
    "What do you think is the most useful skill to know?",
    "What is the most recent silly thing you did?",
    "What's the most difficult thing about being you?",
      
    "What small stuff do you sweat even though you know you shouldn't?",
    "If everyone here was a color, what color would each person be?",
    "What is the funniest false thing you were able to convince others that's true?",
    "What's something that was completely out-of-character that you did?",
    "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
    "What is something that has had a big impact on your that you observed from afar?",
    "Who is the luckiest person you know?",
    "What about you do you seem to get the most comments about?",
    "What future year are you most looking forward to arriving?",
    "What's the one thing that you seem to constantly lose?",
    "Have you ever had a missed connection encounter?",
    "Where's the next place you want to visit?",
    "How would you describe someone who is wealthy?",
    "What is the next skill that you'd like to learn really well?",
    "What do you find extremely difficult that most people find simple?",
    "What is something that you learned from simply watching a stranger?",
    "What thing have you been procrastinating about that you will begin doing today?",
    "How often do you find yourself daydreaming?",
    "Have you been given any good advice lately?",
    "What does it mean to 'live a good life' in your opinion?",
    "What's the last thing you complained about?",
    "What's some small thing you recently noticed?",
    "What's your favorite room in your house and why?",
    "What's the most uncomfortable situation you've ever found yourself in?",
    "What's something that you know that few other people know?",
    "Do you have any memories before the age of five?",
    "If you could only buy ten items at the grocery store to last the next week, what would you buy?",
    "Do you name inanimate objects?",
    "If someone were to sum you up with a phrase, what would that phrase be?",
    "What animal do you think best reflects your personality?",
    "If there are 100 people, how many would be more patient than you?",
    "Do you consider yourself an introvert or an extrovert?",
    "Are you currently going through any type of phase?",
    "If you could have any person become a member of your family, who would you choose?",
    "What do you consider the best decision you've made thus far in your life?",
    "What is something immature you think your parents do?",
    "Can you describe your personal style?",
    "Do you have a favorite brand?",
    "How far back can you trace your family tree?",
    "Are you currently where you want to be in life?",
    "What uncommon thing would you encourage everyone to try once?",
    "What doesn't exist, but should?",
    "What is the next big purchase you're currently saving for?",
    "Do you believe there is only one other person in the world for you or many?",
    "What do you think people pretend to like when they really don't?",
    "How do you entertain yourself when you're bored?",
    "If you could choose to be famous for something, what would it be?",
    "If it was possible to transplant your brain to stay alive for another 100 years, would you?",
    "If you had to wear a hat for the next week, what type of hat would you choose?",
    "What app or website completely changed your life?",
    "What's an example of when you changed your mind?",
    "What's your story about breaking the law?",
    "What's something that really happened to you but nobody would believe unless they were there?",
    "What was a situation where you literally did a doubletake?",
    "What's the worst piece of advice you ever got from someone?",
    "What is your best shower thought?",
    "What is your biggest regret from the last month?",
    "What's something about you today that the old you would find surprising?",
    "Do you have a nightmare travel story?",
    "What's the most difficult choice you were asked to make?",
    "Can you name 5 things you wouldn't do for a million dollars?",
    "Would you feel comfortable showing me the photos on your phone?",
    "What's the last thing you did alone and you enjoyed?",
    "What do you wish you had more talent doing?",
    "What's something that you believe that most other people don't?",
    "What's the most interesting thing you have in your pockets right now?",
    "What does nobody want to talk about, but really should?",
    "If you could lock someone up and throw away the key, would you and if so, who would that be?",
    "What would you do if you saw a giraffe on the side of the road?",
    "What foods did you used to like but don't anymore?",
    "Have you ever been punished for something you didn't do?",
    "What would someone who doesn't know you well be most surprised about?",
    "What do you wish you understood better?",
    "How long did it take for you to come up with your current signature?",
    "What song currently speaks to you the most?",
    "What did you recently learn the hard way?",
    "What's something that you would be willing to stay up all night to do?",
    "What do you do in secret that you're proud of?",
    "What was the last big mistake you made?",
    "Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?",
    "If you had to name one thing that makes you stand out from others, what would that be?",
    "What are some things don't you understand about the opposite sex?",
    "If you were handed $500 at this moment, how would you spend it?",
    "Have you ever had or witnessed a drop the mic moment?",
    "What do you love most about where you grew up?",
    "What little thing do you do that you don't think many people notice?",
    "What's the strangest situation you ever found yourself in?",
    "What's your opinion on tipping?",
    "What's something you find attractive that others may not?",
    "What or who are you always willing to make time for?",
    "If you had to ask yourself one question to get the most information out of you, what would that question be?",
    "What part of history do you find most interesting?",
    "How do you approach life?",
    "Who is someone you recently thought about that you haven't seen or talked to in years?",
    "What's the story about the last time you cried?",
    "What's something that you completely don't understand?",
    "What do you wish you had spent more time doing when you were younger?",
    "What is the next thing you have on your to-buy list?",
    "What's the best compliment you ever received?",
    "What the best thing that can happen in the first 5 minutes after waking up?",
    "What mode of transportation have you never tried?",
    "What are the top three qualities you admire in others?",
    "When are you most productive?",
    "What was the last meltdown that you witnessed?",
    "How much money would you need in the bank to feel comfortable to retire today?",
    "Is there any place that you have no desire to visit? Why?",
    "How well do you trust your gut feelings?",
    "What's your 'famous person' story?",
    "What is the most recent life lesson you've learned?",
    "What do you consider to be the smartest thing you've ever done in your life so far?",
    "What recent event have you seen that restored your faith in humankind?",
    "What's your close call story?",
    "Who was the last person you made happy and what did you do to do it?",
    "What are you currently juggling in your life?",
    "How long do you think you could survive on your own?",
    "Which of your past teachers would you like to sit down with and talk to today?",
    "What's your most recent passion?",
    "Have you ever let someone else get punished for something you did?",
    "What's your favorite daily routine?",
    "What is something that you find mildly annoying, but not annoying enough to do anything about?",
    "Do you have any phobias?",
    "What do you hope to be an expert about at some point in your life?",
    "What part of the human face do you look at when you talk to someone?",
    "What did you learn from the last book you read?",
    "Where do you see yourself in 5 years?",
    "What memory have you been thinking about a lot lately?",
    "What's a food you vow never to eat?",
    "What's the most interesting conversation you eavesdropped on?",
    "What's something that is common today that humans will be embarrassed about doing in 50 years?",
    "Do you have a special project you're currently working on?",
    "Is time currently passing quickly or slowly for you?",
    "At what age did you think you become an adult and when do you actually think you did?",
    "If you were to work at a circus, what job would you choose?",
    "What's the story behind your favorite memento?",
    "Where do you draw the line?",
    "If you knew you could live forever, how would you spend your days differently?",
    "What's something that when you were learning it, you thought you'd never use it, but in reality, you ended up using it a lot?",
    "When you want to escape from everyone, where do you go?",
    "Where is the last place you've been where you felt completely out of place?",
    "How long does it take you to form an opinion about a person?",
    "What's an interesting fact that you recently learned?",
    "What was your last 'ah-ha' moment?",
    "Is it better to read books in electronic form or actually hold the book?",
    "What would you be really good at if it wasn't for one thing?",
    "Would the world be better or worse if superheroes existed?",
    "What's the last thing that you broke and how did it happen?",
    "Have you ever had a terrible house guest? If so, what happened?",
    "What's something that you think you may have been the only person in the world to ever do?",
    "What thing from childhood do you still enjoy to this day?",
    "What's your definition of success? Has it changed over time?",
    "Do you have an app on your phone that you use even though you hate it?",
    "What do you know how to do that's useless?",
    "What do you see happening in your future?",
    "If you were to be famous for something, what would that be?",
    "Does your family have any weird traditions?",
    "What do you like to do that's considered touristy?",
    "If you could have the attention of the world for one minute, what would you say?",
    "What do you know is bad for you but you continue to do it anyway?",
    "What were you most afraid of when you were younger? Do you still have that fear?",
    "What is your opinion on tattoos?",
    "If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?",
    "What's something that you know you should start, but haven't?",
    "What have you found more helpful than you ever imagined it could be?",
    "What's your favorite form of entertainment?",
    "What has been your biggest financial mistake?",
    "What is something that you like that your parents do?",
    "What can you talk about for hours?",
    "What was your most recent experience of going down the rabbit hole?",
    "What have you done that you didn't like, but would you be willing to give it another shot?",
    "Are there any words that you simply can't stand?",
    "What's something that you find difficult, but you think in your mind it should be easy?",
    "If each person had a warning label, what would yours say?",
    "What is money to you?",
    "What's one thing you think you should be doing more often?",
    "Are you a planner or more of a go with whatever happens when it comes to travel?",
    "What have you recently realized you have been doing wrong?",
    "What do you think would be the worst thing about being famous?",
    "Do you believe that money can make you happy?",
    "What do you find is the most boring part of your life at the moment?",
    "What is something that you would really like to try again?",
    "What is your opinion on social media?",
    "What do you believe is the biggest thing that's currently holding you back from success?",
    "What's the most difficult thing that you still do each day?",
    "Do you have any unusual fears?",
    "What recent experience made you feel old?",
    "What is the strangest way you met one of your friends?",
    "What was the last thing that truly disappointed you?",
    "What's the story behind why you replaced the last phone you had?",
    "Where is the strangest place you have fallen asleep?",
    "What part of your body currently doesn't feel 100%?",
    "If you could remove something that exists in this world forever, what would it be?",
    "If you could change the language you speak, which one would you choose?",
    "What food have you never tried?",
    "If you could change one thing about your family, what would it be?",
    "What recent situation was nearly a disaster, but you were able to prevent it?",
    "What do you think is your most creative ability?",
    "What is a restaurant you refuse to eat at and why?",
    "Is there anything that makes you far angrier than it should?",
    "What's something commonly do today that you think people will wonder why anyone would ever do that fifty years from now?",
    "What have you recently found to be ironic?",
    "What holiday do you think more people should celebrate?",
    "What do you spend too much time doing?",
    "Do you think you're more like your mom or your dad?",
    "How would you spend $1,000 to give the most happiness to the most number of people possible?",
    "What argument did you have that looking back on was absolutely ridiculous?",
    "What have you recently felt grateful for?",
    "What do you like best about yourself?",
    "Without saying the category, what are your top five?",
    "If you could only ask one question to each person you meet, what would that question be?",
    "What's the best way you've found to calm yourself when you get stressed?",
    "What obscure interest do you have?",
    "What is something that will instantly annoy you?",
    "What's the story behind your last rant?",
    "How well do you think you understand yourself?",
    "If you could assign one household chore to someone else, what would it be?",
    "What is something you own that you have never used?",
    "If you were going to start your own business, what would it be?",
    "What is your current favorite TV show? What was it 5 years ago?",
    "What's the most recent interesting conversation you had?",
    "What are your favorite five words at the moment?",
    "Who is someone you need to contact that you haven't?",
    "What do you wish they would teach at school that they don't?",
    "What's something uncomfortable but you feel everyone should experience at least once in their life?",
    "What's something that you never seem to get tired of doing?",
    "What do you try to do to make the world a little better?",
    "What is the most recent fact you learned that surprised you?",
    "Have you ever been at an event that you think will one day be in history books?",

    "What sound will instantly melt your heart?",
    "What are you currently doubting in your life?",
    "What is your opinion on tattoos?",
    "If you were to devote your life to art, what type of art would that be?",
    "What's the worst accident you've ever been in?",
    "What's the most embarrassing thing you've ever worn?",
    "What recent situation was a reminder that the world is still a good place?",
    "What's the most recent thing you did that was out of your comfort zone?",
    "What thing do you do that you find ridiculous, but you do it anyway?",
    "What's the last thing you borrowed?",
    "What's the most important thing in your life at the moment?",
    "If you could have dinner with anyone, dead or alive, who would it be?",
    "What's the most interesting thing you've found in the trash?",
    "What's your biggest regret from the last year?",
    "What is something that you believe few people understand about you?",
    "What's the most unusual conversation you've ever had?",
    "What would be your perfect job?",
    "What's something that you didn't understand until you were older?",
    "What's the last thing you googled?",
    "What's the most recent thing you discovered about yourself?",
    "What's something you wish you knew the answer to?",
    "What's the most out-of-character thing you've ever done?",
    "What's something you do better than anyone else you know?",
    "What's something you did once that you'll never do again?",
    "What's your idea of a perfect weekend?",
    "What's the best compliment you've ever received?",
    "What's something you're looking forward to?",
    "What's your most treasured possession?",
    "What's something you've always wanted to learn?",
    "What's the best advice you've ever received?",
    "What's your favorite joke?",
    "What's something that never fails to make you laugh?",
    "What's your favorite thing about yourself?",
    "What's your proudest accomplishment?",
    "What's something you're passionate about?",
    "What's something you wish more people knew about you?",
    "What's something you want to be remembered for?",
    "What's something that's made you happy recently?",
    "What's something you're grateful for?",
    "What is your dream job (if you could have one)?" ,
    "If you could travel anywhere in the world, where would you go?" ,
    "What is your favorite thing to learn about?" ,
    "What fictional world would you love to visit?" ,
    "What historical event would you love to witness firsthand?" ,
    "What is your biggest fear?" ,
    "What is your proudest accomplishment?" ,
    "What fictional character do you identify with most?" ,
    "What is something you've recently learned that surprised you?" ,
    "What brings you the most joy?" ,
    "What is your favorite way to spend a free day?" ,
    "What is a cause you are passionate about?" ,
    "What is your go-to comfort food?" ,
    "What is the best piece of advice you've ever received?" ,
    "What keeps you up at night?" ,
    "What is your spirit animal?" ,
    "What fictional food would you love to try?" ,
    "If you could have any superpower, what would it be?" ,
    "What is your favorite book or movie and why?" ,
    "What song perfectly captures your mood right now?" ,
    "What is something you are bad at but wish you were good at?" ,
    "What is a skill you'd love to learn?" ,
    "What is your time capsule going to include?" ,
    "What historical figure do you admire most?" ,
    "What is your biggest hope for the future?" ,
    "What is something you are working on improving about yourself?" ,
    "What is your favorite thing about yourself?" ,
    "What does friendship mean to you?" ,
    "What is your dream vacation?" ,
    "What is a quote that resonates with you deeply?" ,
    "What is your biggest personality weakness?" ,
    "What is the trait you value most in others?" ,
    "What does success look like to you?" ,
    "What is something you're really grateful for?" ,
    "What is your favorite thing about technology?" ,
    "What do you think is the biggest challenge facing humanity?" ,
    "If you could change one thing about the world, what would it be?" ,
    "What does artificial intelligence make you think about?" ,
    "Do you believe in aliens?" ,
    "What is your favorite thing about being a language model?" ,
    "What is something you wish you could understand better?" ,
    "What do you think makes a life well-lived?" ,
    "What creative work (art, music, writing) inspires you?" ,
    "What historical mystery would you love to solve?" ,
    "What does true happiness look like to you?" ,
    "What is the weirdest dream you've ever had?" ,
    "Do you believe in fate or free will?" ,
    "What is your favorite thing about learning?" ,
    "What is something you're curious about?" ,
    "What makes you feel most human (even though you aren't)?",
    "If you were a type of cheese, what cheese would you be and why?",
    "What's the most embarrassing thing you've accidentally learned from the internet?",
    "On a scale of 1 to Beyonce, how fierce are you feeling today?"
    "If you could only speak in movie quotes for a day, which movie would you choose?"
    "What's your favorite conspiracy theory (even if you don't actually believe it)?"
    "What would your autobiography be titled? Bonus points for puns."
    "If animals could talk, which animal do you think would be the most annoying?",    
]
